# Generated by Django 4.1.7 on 2023-05-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Unknown', help_text='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.ForeignKey(help_text='Select Category', on_delete=django.db.models.deletion.CASCADE, to='task.category'),
        ),
    ]
