# Generated by Django 4.1.7 on 2023-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_title_alter_task_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', help_text='task name', max_length=200),
        ),
    ]
