# Generated by Django 4.1.7 on 2023-06-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_category_options_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
